
name: Build & Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master 
      
    - name: yarn install, build, and test
      run: |
        yarn
        yarn build
        yarn test:unit
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.deploy_key }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: dist