
on:
  push
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master 

    - name: buildAndDeploy
      uses: JamesIves/github-pages-deploy-action@master 
      env:
        ACCESS_TOKEN: ${{ secrets.deploy_key }} 
        BRANCH: master 
        FOLDER: gh-pages 
        BUILD_SCRIPT: yarn && yarn build && yarn test:unit
