
name: Build & Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master 

    - name: Build & Deploy
      uses: JamesIves/github-pages-deploy-action@master 
      env:
        ACCESS_TOKEN: ${{ secrets.deploy_key }} 
        BASE_BRANCH: master
        BRANCH: gh-pages 
        FOLDER: dist 
        BUILD_SCRIPT: yarn && yarn build && yarn test:unit
